#Configuraciones de Funciones
abono.factura.validaterectificadaanulada=true
abono.peaje.validaterectificadaanulada=true

#Reclamaciones
reclamaciones.filtros={reclamacion: 'Reclamación', cliente: 'Cliente', codigoSolicitud: 'Código de solitud'}

scripts.ruta=${C4E_SCRIPTS_ROOT:${C4E_STORAGE_ROOT:${user.home}/Downloads/com4energy}/scripts}
scripts.moverArchivos=${C4E_MOVER_SCRIPT:moverArchivos.bat}

#Configuraciones de liquibase
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml